#!/usr/bin/env python3

from lib.torrent_parser import run_parsing
import sys

parsing_data = {
    "base_url": "https://nyaa.si",
    "search_url": "https://nyaa.si/?f=0&c=0_0&q=",
    "row_selector": "//tbody/tr",
    "data_selectors": {
            "category": "td//a/img[@class='category-icon']/@alt",
            "name": "td//a[contains(@href, 'view') and not(contains(@href, 'comments'))]/text()",
            "size": "(td//a[contains(@href, 'download')]/ancestor::td/following-sibling::td)[1]/text()",
        },
    "next_page_selector": "//*[@class='next']/a/@href",
    "args": sys.argv,
}

run_parsing(parsing_data)


